config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show]
  resources :goals
  resource :session, only: [:new, :create, :destroy]
  resources :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :body, presence: true

  belongs_to :commentable, polymorphic: true
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  validates :name, presence: true

  belongs_to :user
  has_many :comments, as: :commentable
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password
  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: {minimum: 6, allow_nil:true}

  after_initialize :ensure_session_token

  has_many :goals
  has_many :comments, as: :commentable

  def self.find_by_credentials(parameters)
    username = parameters[:username]
    password = parameters[:password]

    user = find_by(username: username)
    user.try(:is_password?, password) ? user : nil
  end

  def password=(password)
    if password.present?
      @password = password
      self.password_digest = BCrypt::Password.create(@password)
    end
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save!

    self.session_token
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :user_params, :current_user, :logged_in?, :logout, :login_user!

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def user_params
    params.require(:user).permit(:username, :password)
  end

  def login_user!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(body: params[:comment][:body],
                           commentable_id: params[:comment][:id],
                           commentable_type: params[:comment][:commentable_type],
                           author_id: params[:comment][:author_id])

    if @comment.save
      if @comment.commentable_type == "Goal"
        redirect_to goal_url(@comment.commentable_id)
      else
        redirect_to user_url(@comment.commentable_id)
      end
    else
      flash[:errors] = @comment.errors.full_messages
      redirect_to :back
    end
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def index
    @goals = Goal.all
    render :index
  end

  def new
    @goal = Goal.new
    render :new
  end

  def show
    @goal = Goal.find(params[:id])
  end

  def create
    @goal = Goal.new(goal_params)
    @goal.completed = false

    if @goal.save
      redirect_to goals_url
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end

  def update
    @goal = Goal.find(params[:id])

    if @goal.update_attributes(goal_params)
      redirect_to goals_url
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :edit
    end
  end

  def edit
    @goal = Goal.find(params[:id])
    render :edit
  end

  def destroy
    Goal.destroy(params[:id])
    redirect_to goals_url
  end

  def goal_params
    params.require(:goal).permit(:name, :public, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.find_by_credentials(user_params)

    if @user.save
      login_user!(@user)
      redirect_to goals_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login_user!(@user)
      redirect_to goals_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/index.html.erb
<ul>

<% @goals.each do |goal| %>
<% if goal.user_id == current_user.id %>
<li>
<%= link_to goal.name, goal_url(goal) %>  -  <%= "Public" if goal.public %>  -
<%= goal.completed ? "Complete!" : "In Progress" %>

</form>

</li>
<% end %>
<% end %>
</ul>

app/views/goals/new.html.erb
<h1>Goalumundo!!!</h1>

<form action="<%= goals_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="goal[user_id]" value="<%= current_user.id %>">

  <label for="goal_name">Name</label>
  <input type="text" name="goal[name]" value="<%= @goal.name %>" id="goal_name">

  <label for="goal_public">Public</label>
  <input type="checkbox" name="goal[public]" id="goal_public">

  <input type="submit" name="name" value="Create Goal">
</form>

app/views/goals/show.html.erb
<%= @goal.name %> -
<%= "Public" if @goal.public %>  -
<%= @goal.completed ? "Complete!" : "In Progress" %>


<h4>Comments</h4>
<% @goal.comments.each do |comment| %>
<%= comment.body %><br><br>
<% end %>

<h5>Add Comment</h5>
<form class="" action="/comments" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="comment[id]" value="<%= @goal.id %>">
  <input type="hidden" name="comment[commentable_type]" value="Goal">

  <label for="comment_body"></label>
  <input type="text" name="comment[body]" id="comment_body"> <br>

  <input type="submit" name="name" value="Comment">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoalSetterApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <% if logged_in? %>
  <%= "Hey " + current_user.username %>
  <%= button_to "Log Out", session_url, method: :delete %>
  <% end %>
  <% if flash[:errors] %>
    <%= render "shared/errors" %>
  <% end %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_errors.html.erb
<% flash[:errors].each do |error| %>
 <%= error %>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="/users" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="user_username">Username</label>
  <input type="text"
         name="user[username]"
         id="user_username"
         value="<%= @user.username %>">
  <br><br>

  <label for="user_password">Password</label>
  <input type="password"
         name="user[password]"
         id="user_password"
         value="<%= @user.password %>">

  <input type="submit" value="Sign Up">

</form>

app/views/users/show.html.erb
<%= @user.username %>


<h4>Comments</h4>
<table>

  <% @user.comments.each do |comment| %>
  <tr>
  <td>
    <%= comment.body %>
  </td>
  <td>
    <%= User.find(comment.author_id).username %>
  </td>
  </tr>
  <br>
  <% end %>
</table>

<h5>Add Comment</h5>
<form class="" action="/comments" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="comment[id]" value="<%= @user.id %>">
  <input type="hidden" name="comment[author_id]" value="<%= current_user.id %>">
  <input type="hidden" name="comment[commentable_type]" value="User">

  <label for="comment_body"></label>
  <input type="text" name="comment[body]" id="comment_body"> <br>

  <input type="submit" name="name" value="Comment">
</form>